-- =============================================================================
-- SEKONDMENT — 0025  EXPERTISE TAXONOMY EXPANSION (Prompt 5, Phase 7)
-- Adds 148 expertise/jurisdiction/service records across priority sectors.
-- Idempotent (on conflict slug do nothing). Continues toward the Stage-1 target;
-- the taxonomy is designed to scale to tens of thousands of records.
-- Runs AFTER 0023 (enum values jurisdiction/service_category must be committed).
-- =============================================================================

insert into expertise_taxonomy (name, slug, type, commercial_value_score, ai_resistance_score, industry_relevance_note) values
  ('Penetration Testing','penetration-testing','expertise',72,78,'Cyber Security'),
  ('Security Operations','security-operations','expertise',72,78,'Cyber Security'),
  ('Incident Response','incident-response','expertise',72,78,'Cyber Security'),
  ('Vulnerability Management','vulnerability-management','expertise',72,78,'Cyber Security'),
  ('Security Architecture','security-architecture','expertise',72,78,'Cyber Security'),
  ('Identity & Access Management','identity-and-access-management','expertise',72,78,'Cyber Security'),
  ('Zero Trust Implementation','zero-trust-implementation','expertise',72,78,'Cyber Security'),
  ('Cloud Security Posture','cloud-security-posture','expertise',72,78,'Cyber Security'),
  ('GDPR Compliance','gdpr-compliance','expertise',72,78,'Cyber Security'),
  ('DORA Compliance','dora-compliance','expertise',72,78,'Cyber Security'),
  ('Threat Intelligence','threat-intelligence','expertise',72,78,'Cyber Security'),
  ('SIEM Implementation','siem-implementation','expertise',72,78,'Cyber Security'),
  ('Endpoint Security','endpoint-security','expertise',72,78,'Cyber Security'),
  ('Security Awareness Training','security-awareness-training','expertise',72,78,'Cyber Security'),
  ('GCP Architecture','gcp-architecture','expertise',62,68,'Cloud'),
  ('Multi-Cloud Strategy','multi-cloud-strategy','expertise',62,68,'Cloud'),
  ('Cloud Cost Optimisation','cloud-cost-optimisation','expertise',62,68,'Cloud'),
  ('Cloud Migration','cloud-migration','expertise',62,68,'Cloud'),
  ('Serverless Architecture','serverless-architecture','expertise',62,68,'Cloud'),
  ('Terraform Infrastructure','terraform-infrastructure','expertise',62,68,'Cloud'),
  ('Cloud Networking','cloud-networking','expertise',62,68,'Cloud'),
  ('Disaster Recovery','disaster-recovery','expertise',62,68,'Cloud'),
  ('CI/CD Pipelines','ci-cd-pipelines','expertise',62,68,'DevOps'),
  ('Container Orchestration','container-orchestration','expertise',62,68,'DevOps'),
  ('Site Reliability Engineering','site-reliability-engineering','expertise',62,68,'DevOps'),
  ('Infrastructure as Code','infrastructure-as-code','expertise',62,68,'DevOps'),
  ('Observability & Monitoring','observability-and-monitoring','expertise',62,68,'DevOps'),
  ('Release Engineering','release-engineering','expertise',62,68,'DevOps'),
  ('GitOps','gitops','expertise',62,68,'DevOps'),
  ('Platform Engineering','platform-engineering','expertise',62,68,'DevOps'),
  ('Data Warehousing','data-warehousing','expertise',62,68,'Data'),
  ('ETL Pipeline Development','etl-pipeline-development','expertise',62,68,'Data'),
  ('Data Modelling','data-modelling','expertise',62,68,'Data'),
  ('Analytics Engineering','analytics-engineering','expertise',62,68,'Data'),
  ('Machine Learning Engineering','machine-learning-engineering','expertise',62,68,'Data'),
  ('Data Governance','data-governance','expertise',62,68,'Data'),
  ('Snowflake Implementation','snowflake-implementation','expertise',62,68,'Data'),
  ('Databricks Implementation','databricks-implementation','expertise',62,68,'Data'),
  ('dbt Implementation','dbt-implementation','expertise',62,68,'Data'),
  ('Real-Time Data Streaming','real-time-data-streaming','expertise',62,68,'Data'),
  ('Contract Drafting','contract-drafting','expertise',72,78,'Legal'),
  ('Commercial Contracts','commercial-contracts','expertise',72,78,'Legal'),
  ('Data Protection Law','data-protection-law','expertise',72,78,'Legal'),
  ('Intellectual Property','intellectual-property','expertise',72,78,'Legal'),
  ('Corporate Law','corporate-law','expertise',72,78,'Legal'),
  ('Regulatory Compliance Law','regulatory-compliance-law','expertise',72,78,'Legal'),
  ('Employment Law','employment-law','expertise',72,78,'Legal'),
  ('Dispute Resolution','dispute-resolution','expertise',72,78,'Legal'),
  ('M&A Legal Support','manda-legal-support','expertise',72,78,'Legal'),
  ('Talent Acquisition','talent-acquisition','expertise',62,68,'HR'),
  ('Compensation & Benefits','compensation-and-benefits','expertise',62,68,'HR'),
  ('Organisational Design','organisational-design','expertise',62,68,'HR'),
  ('Employee Relations','employee-relations','expertise',62,68,'HR'),
  ('Performance Management','performance-management','expertise',62,68,'HR'),
  ('HR Systems Implementation','hr-systems-implementation','expertise',62,68,'HR'),
  ('Diversity & Inclusion','diversity-and-inclusion','expertise',62,68,'HR'),
  ('HR Policy Development','hr-policy-development','expertise',62,68,'HR'),
  ('Technical Recruitment','technical-recruitment','expertise',62,68,'Recruitment'),
  ('Executive Recruitment','executive-recruitment','expertise',62,68,'Recruitment'),
  ('RPO Delivery','rpo-delivery','expertise',62,68,'Recruitment'),
  ('Talent Mapping','talent-mapping','expertise',62,68,'Recruitment'),
  ('Employer Branding','employer-branding','expertise',62,68,'Recruitment'),
  ('Contingent Workforce Management','contingent-workforce-management','expertise',62,68,'Recruitment'),
  ('Quantity Surveying','quantity-surveying','expertise',62,68,'Construction'),
  ('Site Management','site-management','expertise',62,68,'Construction'),
  ('Construction Project Management','construction-project-management','expertise',62,68,'Construction'),
  ('Building Information Modelling','building-information-modelling','expertise',62,68,'Construction'),
  ('Health & Safety Management','health-and-safety-management','expertise',62,68,'Construction'),
  ('Contract Administration','contract-administration','expertise',62,68,'Construction'),
  ('Cost Planning','cost-planning','expertise',62,68,'Construction'),
  ('Structural Engineering','structural-engineering','expertise',62,68,'Construction'),
  ('Mechanical Engineering','mechanical-engineering','expertise',62,68,'Engineering'),
  ('Electrical Engineering','electrical-engineering','expertise',62,68,'Engineering'),
  ('Civil Engineering','civil-engineering','expertise',62,68,'Engineering'),
  ('Process Engineering','process-engineering','expertise',62,68,'Engineering'),
  ('Systems Engineering','systems-engineering','expertise',62,68,'Engineering'),
  ('Quality Engineering','quality-engineering','expertise',62,68,'Engineering'),
  ('Maintenance Engineering','maintenance-engineering','expertise',62,68,'Engineering'),
  ('Design Engineering','design-engineering','expertise',62,68,'Engineering'),
  ('Clinical Governance','clinical-governance','expertise',62,78,'Healthcare'),
  ('Healthcare Compliance','healthcare-compliance','expertise',62,78,'Healthcare'),
  ('Medical Device Regulation','medical-device-regulation','expertise',62,78,'Healthcare'),
  ('Care Quality Management','care-quality-management','expertise',62,78,'Healthcare'),
  ('Health Informatics','health-informatics','expertise',62,78,'Healthcare'),
  ('Clinical Trials Management','clinical-trials-management','expertise',62,78,'Healthcare'),
  ('NHS Procurement','nhs-procurement','expertise',62,78,'Healthcare'),
  ('Patient Safety','patient-safety','expertise',62,78,'Healthcare'),
  ('Renewable Energy Project Management','renewable-energy-project-management','expertise',62,68,'Energy'),
  ('Grid Integration','grid-integration','expertise',62,68,'Energy'),
  ('Energy Trading','energy-trading','expertise',62,68,'Energy'),
  ('Carbon Accounting','carbon-accounting','expertise',62,68,'Energy'),
  ('ESG Reporting','esg-reporting','expertise',62,68,'Energy'),
  ('Solar Project Development','solar-project-development','expertise',62,68,'Energy'),
  ('Wind Project Development','wind-project-development','expertise',62,68,'Energy'),
  ('Energy Efficiency Auditing','energy-efficiency-auditing','expertise',62,68,'Energy'),
  ('Lean Manufacturing','lean-manufacturing','expertise',62,68,'Manufacturing'),
  ('Six Sigma','six-sigma','expertise',62,68,'Manufacturing'),
  ('Production Planning','production-planning','expertise',62,68,'Manufacturing'),
  ('Supply Chain Optimisation','supply-chain-optimisation','expertise',62,68,'Manufacturing'),
  ('Quality Assurance','quality-assurance','expertise',62,68,'Manufacturing'),
  ('ISO9001 Implementation','iso9001-implementation','expertise',62,68,'Manufacturing'),
  ('Industrial Automation','industrial-automation','expertise',62,68,'Manufacturing'),
  ('Inventory Management','inventory-management','expertise',62,68,'Manufacturing'),
  ('Property Valuation','property-valuation','expertise',62,68,'Real Estate'),
  ('Asset Management','asset-management','expertise',62,68,'Real Estate'),
  ('Lease Advisory','lease-advisory','expertise',62,68,'Real Estate'),
  ('Development Appraisal','development-appraisal','expertise',62,68,'Real Estate'),
  ('Facilities Management','facilities-management','expertise',62,68,'Real Estate'),
  ('Property Acquisition','property-acquisition','expertise',62,68,'Real Estate'),
  ('Real Estate Finance','real-estate-finance','expertise',62,68,'Real Estate'),
  ('Planning & Development','planning-and-development','expertise',62,68,'Real Estate'),
  ('Management Consulting','management-consulting','expertise',72,68,'Professional Services'),
  ('Strategy Consulting','strategy-consulting','expertise',72,68,'Professional Services'),
  ('Operational Due Diligence','operational-due-diligence','expertise',72,68,'Professional Services'),
  ('Post-Merger Integration','post-merger-integration','expertise',72,68,'Professional Services'),
  ('Cost Reduction','cost-reduction','expertise',72,68,'Professional Services'),
  ('Outsourcing Advisory','outsourcing-advisory','expertise',72,68,'Professional Services'),
  ('Digital Transformation Advisory','digital-transformation-advisory','expertise',72,68,'Professional Services'),
  ('Enterprise Risk Management','enterprise-risk-management','expertise',72,78,'Risk'),
  ('Operational Risk','operational-risk','expertise',72,78,'Risk'),
  ('Credit Risk','credit-risk','expertise',72,78,'Risk'),
  ('Market Risk','market-risk','expertise',72,78,'Risk'),
  ('Risk Modelling','risk-modelling','expertise',72,78,'Risk'),
  ('Business Continuity Planning','business-continuity-planning','expertise',72,78,'Risk'),
  ('Internal Audit','internal-audit','expertise',72,78,'Risk'),
  ('Fraud Risk Management','fraud-risk-management','expertise',72,78,'Risk'),
  ('Jersey (jurisdiction)','jersey-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Guernsey (jurisdiction)','guernsey-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Isle of Man (jurisdiction)','isle-of-man-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('United Kingdom (jurisdiction)','united-kingdom-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Ireland (jurisdiction)','ireland-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Luxembourg (jurisdiction)','luxembourg-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Cayman Islands (jurisdiction)','cayman-islands-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('BVI (jurisdiction)','bvi-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('UAE (jurisdiction)','uae-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Switzerland (jurisdiction)','switzerland-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Singapore (jurisdiction)','singapore-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('United States (jurisdiction)','united-states-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Malta (jurisdiction)','malta-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Gibraltar (jurisdiction)','gibraltar-jurisdiction','jurisdiction',60,85,'Jurisdiction'),
  ('Advisory','advisory-service','service_category',55,60,'Service'),
  ('Implementation','implementation-service','service_category',55,60,'Service'),
  ('Managed Service','managed-service-service','service_category',55,60,'Service'),
  ('Interim Leadership','interim-leadership-service','service_category',55,60,'Service'),
  ('Audit & Assurance','audit-and-assurance-service','service_category',55,60,'Service'),
  ('Project Delivery','project-delivery-service','service_category',55,60,'Service'),
  ('Training & Enablement','training-and-enablement-service','service_category',55,60,'Service'),
  ('Staff Augmentation','staff-augmentation-service','service_category',55,60,'Service')
on conflict (slug) do nothing;
