-- =============================================================================
-- SEKONDMENT — 0029  RESEARCH-BACKED TAXONOMY + DEMAND DATA (Prompt: research)
-- 62 expertise records across 14 sectors, with commercial_value_score,
-- ai_resistance_score and demand_weight set from 2026 market research (fractional
-- leadership, cyber, AI/data, compliance, energy/HSE, healthcare, defence...).
-- Idempotent. Runs after 0023 (enum types) / 0025 (earlier expansion).
-- =============================================================================

insert into expertise_taxonomy (name, slug, type, commercial_value_score, ai_resistance_score, demand_weight, industry_relevance_note) values
  ('Machine Learning Engineering','machine-learning-engineering','expertise',86,60,100,'Data & AI'),
  ('Agentic AI Development','agentic-ai-development','expertise',90,80,100,'Data & AI'),
  ('LLM / Prompt Engineering','llm-prompt-engineering','expertise',78,40,100,'Data & AI'),
  ('MLOps & Model Deployment','mlops-model-deployment','expertise',80,60,100,'Data & AI'),
  ('AI Governance & Ethics','ai-governance-ethics','expertise',81,100,100,'Data & AI'),
  ('Data Engineering','data-engineering','expertise',75,60,100,'Data & AI'),
  ('Data Governance','data-governance','expertise',76,80,100,'Data & AI'),
  ('Analytics Engineering (dbt)','analytics-engineering-dbt','expertise',73,60,80,'Data & AI'),
  ('Fractional AI Officer','fractional-ai-officer','role',93,100,100,'Data & AI'),
  ('Penetration Testing','penetration-testing','expertise',80,80,100,'Cyber Security'),
  ('Security Architecture','security-architecture','expertise',83,80,100,'Cyber Security'),
  ('Incident Response & Forensics','incident-response-forensics','expertise',81,80,100,'Cyber Security'),
  ('Zero Trust Implementation','zero-trust-implementation','expertise',81,80,100,'Cyber Security'),
  ('Cloud Security (CSPM)','cloud-security-cspm','expertise',80,80,100,'Cyber Security'),
  ('AI Security / Red Teaming','ai-security-red-teaming','expertise',86,100,100,'Cyber Security'),
  ('SOC2 Readiness','soc2-readiness','expertise',75,80,100,'Cyber Security'),
  ('ISO27001 Implementation','iso27001-implementation','expertise',75,80,100,'Cyber Security'),
  ('Fractional CISO','fractional-ciso','role',90,100,100,'Cyber Security'),
  ('Cloud Architecture (AWS)','cloud-architecture-aws','expertise',78,60,100,'Technology'),
  ('Azure Architecture','azure-architecture','expertise',76,60,80,'Technology'),
  ('Kubernetes / Platform Engineering','kubernetes-platform-engineering','expertise',80,60,100,'Technology'),
  ('Site Reliability Engineering','site-reliability-engineering','expertise',78,60,80,'Technology'),
  ('Terraform / IaC','terraform-iac','expertise',76,60,80,'Technology'),
  ('Stripe Connect Implementation','stripe-connect-implementation','expertise',75,60,80,'Technology'),
  ('Microsoft 365 Migration','microsoft-365-migration','expertise',70,40,80,'Technology'),
  ('Fractional CTO','fractional-cto','role',86,100,100,'Technology'),
  ('AML Review','aml-review','expertise',71,80,100,'Finance'),
  ('KYC Review','kyc-review','expertise',70,60,100,'Finance'),
  ('Trust Administration','trust-administration','expertise',71,80,80,'Finance'),
  ('Fund Administration','fund-administration','expertise',72,80,80,'Finance'),
  ('Regulatory Reporting','regulatory-reporting','expertise',73,80,80,'Finance'),
  ('Financial Modelling','financial-modelling','expertise',75,60,80,'Finance'),
  ('Fractional CFO','fractional-cfo','role',86,100,100,'Leadership'),
  ('Fractional Financial Controller','fractional-financial-controller','role',78,80,80,'Finance'),
  ('Enterprise Risk Management','enterprise-risk-management','expertise',78,100,80,'Risk'),
  ('Operational Resilience (DORA)','operational-resilience-dora','expertise',80,100,100,'Risk'),
  ('Internal Audit','internal-audit','expertise',73,80,80,'Risk'),
  ('Data Protection / GDPR','data-protection-gdpr','expertise',76,80,100,'Legal'),
  ('Commercial Contracts','commercial-contracts','expertise',75,80,80,'Legal'),
  ('M&A Legal Support','m&a-legal-support','expertise',83,100,80,'Legal'),
  ('Meta Ads Lead Generation','meta-ads-lead-generation','expertise',67,40,80,'Marketing'),
  ('Google Ads / PPC','google-ads-ppc','expertise',67,40,80,'Marketing'),
  ('SEO Strategy','seo-strategy','expertise',66,40,60,'Marketing'),
  ('HubSpot / Lifecycle Automation','hubspot-lifecycle-automation','expertise',68,40,80,'Marketing'),
  ('Fractional CMO','fractional-cmo','role',81,80,100,'Marketing'),
  ('Business Transformation','business-transformation','expertise',80,80,80,'Operations'),
  ('Change Management','change-management','expertise',75,80,80,'Operations'),
  ('Supply Chain Optimisation','supply-chain-optimisation','expertise',76,80,100,'Operations'),
  ('Fractional COO','fractional-coo','role',85,100,100,'Leadership'),
  ('PMO / Programme Management','pmo-programme-management','expertise',73,60,80,'Operations'),
  ('Renewable Energy Project Management','renewable-energy-project-management','expertise',76,80,100,'Energy'),
  ('Carbon Accounting & ESG Reporting','carbon-accounting-esg-reporting','expertise',75,80,100,'Energy'),
  ('Grid Integration','grid-integration','expertise',78,80,80,'Energy'),
  ('HSE / Health & Safety Management','hse-health-safety-management','expertise',71,80,100,'Construction'),
  ('Quantity Surveying','quantity-surveying','expertise',73,80,80,'Construction'),
  ('BIM Coordination','bim-coordination','expertise',71,60,80,'Construction'),
  ('Clinical Governance','clinical-governance','expertise',75,100,100,'Healthcare'),
  ('Medical Device Regulation','medical-device-regulation','expertise',78,100,100,'Healthcare'),
  ('Health Informatics','health-informatics','expertise',76,80,80,'Healthcare'),
  ('Lean Manufacturing / Six Sigma','lean-manufacturing-six-sigma','expertise',73,80,80,'Manufacturing'),
  ('Industrial Automation','industrial-automation','expertise',76,80,100,'Manufacturing'),
  ('Defence Procurement','defence-procurement','expertise',80,100,100,'Defence')
on conflict (slug) do nothing;
